-- ═══════════════════════════════════════════════════════════════════════════════════════════
-- QMULATE — HAND-AUTHORED constraints, triggers and guards migration.
--
-- THIS FILE IS NOT GENERATED BY PRISMA AND MUST NEVER BE OVERWRITTEN BY `prisma migrate dev`.
-- See `packages/database/prisma/sql/README.md` before touching it.
--
-- It installs the five database-level controls that application code cannot be trusted to
-- enforce, because the whole point of each of them is that a privileged operator (including a
-- migration, a backfill, or a DBA with a psql prompt) must not be able to get around it:
--
--   1. AUDIT APPEND-ONLY GUARD          gate G-1 / NFR-04   -> `audit_event` may only be INSERTed
--   2. LEAST-PRIVILEGE RUNTIME ROLE     gate G-1 / NFR-04   -> `qmulate_app_runtime` (defence in depth)
--   3. SHART AL-WAQIF IMMUTABILITY      Binding rule 1      -> amendable only by a reserved matter
--   4. CORPUS / INCOME GUARD            Binding rule 1      -> every REVENUE receipt is classified
--   5. DOCUMENT RETENTION GUARD         NFR-07 / BR-702     -> no hard delete inside retention
--
-- Plus two integrity constraints the Prisma schema language cannot express:
--   6. `setting_global_key_unique`      -- Postgres treats NULLs as distinct, so `@@unique([waqfId,key])`
--                                          alone does NOT stop duplicate GLOBAL setting rows
--   7. `audit_chain_head_singleton`     -- the chain head is a singleton row, pinned to id = 1
--
-- ── NAMING ───────────────────────────────────────────────────────────────────────────────────
-- Table names are snake_case singular (via Prisma `@@map`); COLUMN names stay Prisma camelCase.
-- Every column identifier below is therefore DOUBLE-QUOTED. Unquoted identifiers would be
-- folded to lower case by Postgres and would not match.
--
-- ── IDEMPOTENCY (assertion A12) ──────────────────────────────────────────────────────────────
-- Every statement is re-runnable: `CREATE OR REPLACE FUNCTION`, `DROP TRIGGER IF EXISTS` before
-- `CREATE TRIGGER`, `CREATE ... IF NOT EXISTS`, and a `pg_constraint` existence check before
-- each `ALTER TABLE ... ADD CONSTRAINT` (Postgres has no `ADD CONSTRAINT IF NOT EXISTS`).
-- Running this whole file twice against the same database succeeds with no error.
--
-- ── RE-ENTRY POINT ───────────────────────────────────────────────────────────────────────────
-- All table-dependent DDL lives inside `qmulate_apply_guards()`. After ANY schema change that
-- recreates a guarded table, re-apply the guards with:  SELECT qmulate_apply_guards();
-- ═══════════════════════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════════════════════
-- SECTION 0 — HELPERS
--
-- plpgsql function BODIES are only syntax-checked at creation time; the tables they reference
-- are resolved at call time. Everything in this section is therefore safe to create even if the
-- Prisma-generated init migration has not run yet.
-- ═══════════════════════════════════════════════════════════════════════════════════════════

-- Add a CHECK constraint only if it does not already exist (no `ADD CONSTRAINT IF NOT EXISTS`
-- in Postgres). Idempotency helper for assertion A12.
CREATE OR REPLACE FUNCTION qmulate_add_check(p_table text, p_name text, p_expr text)
RETURNS void
LANGUAGE plpgsql
AS $qm_add_check$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = p_name
      AND conrelid = format('public.%I', p_table)::regclass
  ) THEN
    EXECUTE format('ALTER TABLE public.%I ADD CONSTRAINT %I CHECK (%s)', p_table, p_name, p_expr);
  END IF;
END;
$qm_add_check$;


-- ═══════════════════════════════════════════════════════════════════════════════════════════
-- SECTION 1 — TRIGGER FUNCTIONS
-- ═══════════════════════════════════════════════════════════════════════════════════════════

-- ── 1a. AUDIT APPEND-ONLY (gate G-1 / NFR-04) ────────────────────────────────────────────────
-- The audit trail is tamper-EVIDENT by its sha256 hash chain and tamper-RESISTANT by this
-- trigger. The trigger is the LOAD-BEARING control, not the GRANTs in section 2: on Railway the
-- runtime normally connects as the database OWNER, and an owner bypasses GRANTs — but NOT
-- triggers. Assertions A1/A2/A3 and verification V-7 must pass on the strength of this function
-- alone.
--
-- LIMITATION, stated rather than papered over: a trigger cannot record the rejected attempt into
-- the very table it is protecting. Evidence for a raw-SQL attempt is the Postgres error log. The
-- API-layer path records an `ACCESS_DENIED` audit event instead.
CREATE OR REPLACE FUNCTION qmulate_audit_log_immutable()
RETURNS trigger
LANGUAGE plpgsql
AS $qm_audit_immutable$
BEGIN
  RAISE EXCEPTION
    'audit_event is append-only; % rejected. The QMULATE audit trail is tamper-evident and may '
    'never be updated, deleted or truncated (NFR-04 / gate G-1). Correct a mis-recorded event by '
    'appending a compensating event, never by editing history.',
    TG_OP
    USING ERRCODE = '42501';
  RETURN NULL; -- unreachable; present so the function is well-formed
END;
$qm_audit_immutable$;

-- Alias under the name used by the E1 build contract (§E4), so either name resolves.
CREATE OR REPLACE FUNCTION qmulate_audit_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $qm_audit_reject$
BEGIN
  RAISE EXCEPTION
    'audit_event is append-only; % rejected (NFR-04 / gate G-1).', TG_OP
    USING ERRCODE = '42501';
  RETURN NULL;
END;
$qm_audit_reject$;


-- ── 1a-bis. THE CHAIN HEAD IS A HIGH-WATER MARK ──────────────────────────────────────────────
-- `audit_chain_head` has to stay UPDATE-able: the audit extension advances it once per
-- transaction. But it must only ever move FORWARD. Rewinding it is the second half of a tail
-- truncation — delete the newest events, then point the head at the new tail — and that
-- combination is invisible to `verifyChain()`, which validates links and hashes but has no
-- independent notion of the chain's length.
CREATE OR REPLACE FUNCTION qmulate_audit_chain_head_forward_only()
RETURNS trigger
LANGUAGE plpgsql
AS $qm_head_forward$
BEGIN
  IF NEW."lastId" < OLD."lastId" THEN
    RAISE EXCEPTION
      'audit_chain_head may only move forward: lastId % -> % rejected. Rewinding the head is '
      'how a truncated trail is made to verify clean (NFR-04 / gate G-1).',
      OLD."lastId", NEW."lastId"
      USING ERRCODE = '42501';
  END IF;

  -- Same id, different hash = the same position re-attested to a different value.
  IF NEW."lastId" = OLD."lastId" AND NEW."lastRowHash" IS DISTINCT FROM OLD."lastRowHash" THEN
    RAISE EXCEPTION
      'audit_chain_head lastRowHash may not be rewritten in place at lastId % (NFR-04 / gate G-1).',
      OLD."lastId"
      USING ERRCODE = '42501';
  END IF;

  RETURN NEW;
END;
$qm_head_forward$;


-- ── 1b. SHART AL-WAQIF IMMUTABILITY (Binding rule 1) ─────────────────────────────────────────
-- The founder's conditions are WRITE-ONCE. INSERT is unguarded; UPDATE is guarded. A migration
-- or a backfill hits this trigger too — that is precisely the point.
--
-- The only way through is a transaction-local GUC that `withReservedMatter()` sets AFTER it has
-- verified an APPROVED, maker != checker `ApprovalRequest` of type RESERVED_MATTER for this
-- waqf:  SELECT set_config('qmulate.reserved_matter_approval_id', '<approvalRequestId>', true);
-- `true` = transaction-local, so it evaporates on COMMIT/ROLLBACK and cannot leak to the next
-- statement on a pooled connection.
--
-- The GUC name is exported from TypeScript as `RESERVED_MATTER_APPROVAL_GUC`
-- (packages/database/src/context.ts) — change it in both places or not at all.
CREATE OR REPLACE FUNCTION qmulate_shart_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $qm_shart_guard$
DECLARE
  approval text;
  changed  text := NULL;
BEGIN
  -- The Shart itself and its version/effective-date stamp.
  IF NEW."shartAlWaqif" IS DISTINCT FROM OLD."shartAlWaqif" THEN
    changed := 'shartAlWaqif';
  ELSIF NEW."shartAlWaqifVersion" IS DISTINCT FROM OLD."shartAlWaqifVersion" THEN
    changed := 'shartAlWaqifVersion';
  ELSIF NEW."shartAlWaqifSetAt" IS DISTINCT FROM OLD."shartAlWaqifSetAt" THEN
    changed := 'shartAlWaqifSetAt';
  ELSIF NEW."shartAlWaqifSetAtHijri" IS DISTINCT FROM OLD."shartAlWaqifSetAtHijri" THEN
    changed := 'shartAlWaqifSetAtHijri';

  -- ── DEED / CERTIFICATE IDENTITY ────────────────────────────────────────────────────────────
  -- TODO(surface): SCOPE — the E1 contract's trigger guards only the Shart columns; the task
  -- brief additionally names "the deed/certificate identity columns". Both are guarded here
  -- because a silent re-pointing of a waqf to a different deed is as damaging as editing the
  -- Shart. This is a SCOPE decision, not a resolved one: if a mis-keyed certificate number must
  -- stay an ordinary correction, delete the two branches below and re-run this file.
  ELSIF NEW."certificateNumber" IS DISTINCT FROM OLD."certificateNumber" THEN
    changed := 'certificateNumber';
  ELSIF NEW."deedNumber" IS DISTINCT FROM OLD."deedNumber" THEN
    changed := 'deedNumber';
  END IF;

  IF changed IS NOT NULL THEN
    approval := current_setting('qmulate.reserved_matter_approval_id', true);
    IF approval IS NULL OR btrim(approval) = '' THEN
      RAISE EXCEPTION
        'shart_al_waqif is immutable: column "%" on waqf % may be amended only through an '
        'authority-gated reserved matter (Binding rule 1). Set '
        'qmulate.reserved_matter_approval_id inside the transaction via withReservedMatter().',
        changed, OLD."id"
        USING ERRCODE = '42501';
    END IF;
  END IF;

  RETURN NEW;
END;
$qm_shart_guard$;


-- ── 1c. DOCUMENT RETENTION GUARD (NFR-07 / BR-702) ───────────────────────────────────────────
-- Deletion inside the retention window is SOFT ONLY (`deletedAt`). A hard DELETE is refused
-- while the document is under legal hold or still inside its >= 10-year retention window (the
-- floor itself lives in `Setting['retention.minimumYears']`, never in code).
-- ⚠ unverified — confirm vs primary law (the 10-year floor)
CREATE OR REPLACE FUNCTION qmulate_document_retention_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $qm_doc_retention$
BEGIN
  IF OLD."legalHold" THEN
    RAISE EXCEPTION
      'document % is under LEGAL HOLD and cannot be deleted (NFR-07 / BR-702). Release the hold '
      'through the documented legal-hold workflow first.', OLD."id"
      USING ERRCODE = '42501';
  END IF;

  IF OLD."retentionUntil" > now() THEN
    RAISE EXCEPTION
      'document % is inside its retention window (until %) and cannot be hard-deleted '
      '(NFR-07 / BR-702). Use a soft delete: set "deletedAt".', OLD."id", OLD."retentionUntil"
      USING ERRCODE = '42501';
  END IF;

  RETURN OLD;
END;
$qm_doc_retention$;


-- The DELETE guard above reads `legalHold` and `retentionUntil` from the row — so on its own it
-- is only as strong as those two columns. Found by adversarial review: a caller could simply
--
--     UPDATE "document" SET "legalHold" = false, "retentionUntil" = now() - interval '1 day';
--     DELETE FROM "document" WHERE …;
--
-- and the retention guard would wave the delete through, having been told the window had closed.
-- Retention may therefore only ever be EXTENDED, and a legal hold only released deliberately.
--
-- Releasing a hold is an audited, TOTP-gated action (§12) that does not exist until E9/E11, so
-- for now the only sanctioned release path is the same reserved-matter GUC the Shart guard uses.
-- That keeps the door closed by default instead of leaving it ajar.
CREATE OR REPLACE FUNCTION qmulate_document_retention_forward_only()
RETURNS trigger
LANGUAGE plpgsql
AS $qm_doc_forward$
DECLARE
  approval text := current_setting('qmulate.reserved_matter_approval_id', true);
BEGIN
  IF approval IS NOT NULL AND approval <> '' THEN
    RETURN NEW; -- authority-gated release; the approval id is recorded by the caller
  END IF;

  IF NEW."retentionUntil" < OLD."retentionUntil" THEN
    RAISE EXCEPTION
      'document %: retentionUntil may only be extended (% -> % rejected). Shortening retention '
      'is how a delete guard is talked into permitting a delete (NFR-07 / BR-702).',
      OLD."id", OLD."retentionUntil", NEW."retentionUntil"
      USING ERRCODE = '42501';
  END IF;

  IF OLD."legalHold" AND NOT NEW."legalHold" THEN
    RAISE EXCEPTION
      'document %: a legal hold may only be released through the audited, authority-gated '
      'workflow (NFR-07 / BR-702, §12). Direct clearing of legalHold is rejected.', OLD."id"
      USING ERRCODE = '42501';
  END IF;

  RETURN NEW;
END;
$qm_doc_forward$;

CREATE OR REPLACE FUNCTION qmulate_document_reject_truncate()
RETURNS trigger
LANGUAGE plpgsql
AS $qm_doc_truncate$
BEGIN
  RAISE EXCEPTION
    'TRUNCATE on "document" is refused: it would bypass the per-row retention and legal-hold '
    'guard (NFR-07 / BR-702).'
    USING ERRCODE = '42501';
  RETURN NULL;
END;
$qm_doc_truncate$;


-- ═══════════════════════════════════════════════════════════════════════════════════════════
-- SECTION 2 — LEAST-PRIVILEGE RUNTIME ROLE (defence in depth)
--
-- ⚠ OPERATIONAL NOTE (surfaced, not resolved): on Railway the application normally connects as
-- the database OWNER, and an owner BYPASSES table GRANTs. These grants therefore prove that the
-- least-privilege posture EXISTS (assertion A4); they do not by themselves prove that the
-- running application is constrained by it. Provision a dedicated non-owner login role and a
-- separate `APP_DATABASE_URL` before any environment carries data beyond the fixture.
--
-- Role creation needs CREATEROLE. Where the connection lacks it (some managed Postgres tiers,
-- shadow databases used by `prisma migrate dev`) the migration emits a NOTICE and continues, so
-- a developer is never blocked. CI and production MUST run this migration with a privileged
-- connection, otherwise assertion A4 fails.
-- ═══════════════════════════════════════════════════════════════════════════════════════════

DO $qm_role$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'qmulate_app_runtime') THEN
    BEGIN
      CREATE ROLE qmulate_app_runtime NOLOGIN;
      RAISE NOTICE 'QMULATE: created role qmulate_app_runtime (NOLOGIN).';
    EXCEPTION
      WHEN insufficient_privilege THEN
        RAISE NOTICE
          'QMULATE: could not CREATE ROLE qmulate_app_runtime — this connection lacks CREATEROLE. '
          'The append-only TRIGGER still protects audit_event, but assertion A4 (privilege '
          'assertions) will fail until this migration is applied with a privileged connection.';
      WHEN duplicate_object THEN
        NULL; -- lost a race with a concurrent deploy; nothing to do
    END;
  END IF;
END
$qm_role$;


-- ═══════════════════════════════════════════════════════════════════════════════════════════
-- SECTION 3 — qmulate_apply_guards()
--
-- Everything that needs the tables to exist. Kept in one idempotent function so it can be
-- re-applied after any schema regeneration with a single `SELECT qmulate_apply_guards();`.
-- ═══════════════════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION qmulate_apply_guards()
RETURNS void
LANGUAGE plpgsql
AS $qm_apply_guards$
DECLARE
  audit_seq text;
BEGIN
  -- ─────────────────────────────────────────────────────────────────────────────────────────
  -- 3.1 AUDIT APPEND-ONLY TRIGGERS (gate G-1, assertions A1–A3)
  --
  -- THREE triggers, deliberately overlapping:
  --   • statement-level UPDATE/DELETE  — fires even for a statement that matches ZERO rows, so
  --                                      a probing `UPDATE ... WHERE false` is still refused
  --   • statement-level TRUNCATE       — TRUNCATE never fires row triggers; without this it
  --                                      would wipe the trail unopposed
  --   • row-level UPDATE/DELETE        — belt and braces, and names the offending row
  -- TRUNCATE is registered as its own trigger rather than combined with UPDATE/DELETE so that
  -- the statement is portable across every supported Postgres version.
  -- ─────────────────────────────────────────────────────────────────────────────────────────
  DROP TRIGGER IF EXISTS audit_event_no_mutate ON "audit_event";
  CREATE TRIGGER audit_event_no_mutate
    BEFORE UPDATE OR DELETE ON "audit_event"
    FOR EACH STATEMENT EXECUTE FUNCTION qmulate_audit_log_immutable();

  DROP TRIGGER IF EXISTS audit_event_no_truncate ON "audit_event";
  CREATE TRIGGER audit_event_no_truncate
    BEFORE TRUNCATE ON "audit_event"
    FOR EACH STATEMENT EXECUTE FUNCTION qmulate_audit_log_immutable();

  DROP TRIGGER IF EXISTS audit_event_no_mutate_row ON "audit_event";
  CREATE TRIGGER audit_event_no_mutate_row
    BEFORE UPDATE OR DELETE ON "audit_event"
    FOR EACH ROW EXECUTE FUNCTION qmulate_audit_log_immutable();

  -- The chain head is bookkeeping, not evidence, so it stays UPDATE-able — but it is a
  -- singleton and must never be deleted or truncated.
  DROP TRIGGER IF EXISTS audit_chain_head_no_truncate ON "audit_chain_head";
  CREATE TRIGGER audit_chain_head_no_truncate
    BEFORE TRUNCATE ON "audit_chain_head"
    FOR EACH STATEMENT EXECUTE FUNCTION qmulate_audit_log_immutable();

  DROP TRIGGER IF EXISTS audit_chain_head_no_delete ON "audit_chain_head";
  CREATE TRIGGER audit_chain_head_no_delete
    BEFORE DELETE ON "audit_chain_head"
    FOR EACH STATEMENT EXECUTE FUNCTION qmulate_audit_log_immutable();

  -- ─────────────────────────────────────────────────────────────────────────────────────────
  -- The chain head only ever moves FORWARD.
  --
  -- Found by adversarial review: because the head was freely UPDATE-able, an attacker could
  -- delete the newest N events and then rewind `lastId` / `lastRowHash` to match the new tail.
  -- `verifyChain()` walks links and recomputes hashes — it has no independent notion of how
  -- long the chain should be — so the doctored database verified clean and the whole G-1 suite
  -- passed over it. Tail truncation was the one tampering the trail could not see.
  --
  -- Forbidding a decrease closes it: the head is a high-water mark, so rewinding it now fails
  -- and the truncation is left detectable as head-ahead-of-tail. (External anchoring of the
  -- latest hash remains the §12 P1 hardening; this is the cheap half that works today.)
  DROP TRIGGER IF EXISTS audit_chain_head_forward_only ON "audit_chain_head";
  CREATE TRIGGER audit_chain_head_forward_only
    BEFORE UPDATE ON "audit_chain_head"
    FOR EACH ROW EXECUTE FUNCTION qmulate_audit_chain_head_forward_only();

  -- ─────────────────────────────────────────────────────────────────────────────────────────
  -- 3.2 SHART AL-WAQIF IMMUTABILITY (Binding rule 1, assertion A11)
  -- ─────────────────────────────────────────────────────────────────────────────────────────
  DROP TRIGGER IF EXISTS waqf_shart_immutable ON "waqf";
  CREATE TRIGGER waqf_shart_immutable
    BEFORE UPDATE ON "waqf"
    FOR EACH ROW EXECUTE FUNCTION qmulate_shart_guard();

  -- ─────────────────────────────────────────────────────────────────────────────────────────
  -- 3.3 DOCUMENT RETENTION GUARD (NFR-07 / BR-702)
  -- ─────────────────────────────────────────────────────────────────────────────────────────
  DROP TRIGGER IF EXISTS document_retention_guard ON "document";
  CREATE TRIGGER document_retention_guard
    BEFORE DELETE ON "document"
    FOR EACH ROW EXECUTE FUNCTION qmulate_document_retention_guard();

  DROP TRIGGER IF EXISTS document_retention_forward_only ON "document";
  CREATE TRIGGER document_retention_forward_only
    BEFORE UPDATE ON "document"
    FOR EACH ROW EXECUTE FUNCTION qmulate_document_retention_forward_only();

  DROP TRIGGER IF EXISTS document_no_truncate ON "document";
  CREATE TRIGGER document_no_truncate
    BEFORE TRUNCATE ON "document"
    FOR EACH STATEMENT EXECUTE FUNCTION qmulate_document_reject_truncate();

  -- ─────────────────────────────────────────────────────────────────────────────────────────
  -- 3.4 CORPUS / INCOME GUARD ON "transaction" (Binding rule 1, assertion A13)
  --
  -- WHAT THESE DO AND DO NOT DECIDE.
  -- They enforce the STRUCTURE of corpus/income segregation, which is a safe invariant:
  --   • every REVENUE receipt is classified income-vs-capital AT ENTRY;
  --   • a CAPITAL receipt always names the corpus event that produced it;
  --   • an EXPENSE — an outflow, neither ghallah nor asl inflow — carries no receipt class;
  --   • the distribution waterfall's only legal input is type = REVENUE AND receiptClass = INCOME.
  --
  -- TODO(surface): FIQH — they do NOT decide WHICH receipt is which. The ADR asserts
  -- rent = income and sale / istibdal / expropriation proceeds = capital, but BUILD-PLAN records
  -- the Sharia review as UNSIGNED. Open: lease premium / key money; insurance proceeds on a
  -- destroyed building; rent arrears collected after an istibdal (old corpus or new?); whether an
  -- income-funded siyana reserve becomes corpus once accumulated; whether a CAPITAL receipt
  -- belongs in `transaction` at all or in a separate `CorpusMovement`.
  --
  -- DELIBERATELY ABSENT: a money-conservation CHECK on "distribution". Conservation is a §08
  -- ENGINE invariant (I1), and the fixture's own historical `dist-001` violates it, so a CHECK
  -- would make the fixture unseedable. See `Distribution.computationTrace`.
  -- ─────────────────────────────────────────────────────────────────────────────────────────
  PERFORM qmulate_add_check(
    'transaction',
    'transaction_revenue_requires_receipt_class',
    '"type" <> ''REVENUE'' OR "receiptClass" IS NOT NULL'
  );
  PERFORM qmulate_add_check(
    'transaction',
    'transaction_expense_has_no_receipt_class',
    '"type" <> ''EXPENSE'' OR ("receiptClass" IS NULL AND "capitalSource" IS NULL)'
  );
  PERFORM qmulate_add_check(
    'transaction',
    'transaction_expense_requires_category',
    '"type" <> ''EXPENSE'' OR "expenseCategory" IS NOT NULL'
  );
  PERFORM qmulate_add_check(
    'transaction',
    'transaction_capital_requires_source',
    '"receiptClass" IS DISTINCT FROM ''CAPITAL'' OR "capitalSource" IS NOT NULL'
  );
  PERFORM qmulate_add_check(
    'transaction',
    'transaction_income_has_no_capital_source',
    '"receiptClass" IS DISTINCT FROM ''INCOME'' OR "capitalSource" IS NULL'
  );
  PERFORM qmulate_add_check(
    'transaction',
    'transaction_capital_other_requires_note',
    '"capitalSource" IS DISTINCT FROM ''OTHER'' OR "capitalSourceNoteAr" IS NOT NULL'
  );
  PERFORM qmulate_add_check(
    'transaction',
    'transaction_amount_nonnegative',
    '"amountSar" >= 0'
  );

  -- ─────────────────────────────────────────────────────────────────────────────────────────
  -- 3.5 SETTING — global-key uniqueness
  -- `@@unique([waqfId, key])` does NOT stop two global rows for the same key, because Postgres
  -- treats NULLs as distinct. A partial unique index closes it.
  -- ─────────────────────────────────────────────────────────────────────────────────────────
  CREATE UNIQUE INDEX IF NOT EXISTS setting_global_key_unique
    ON "setting" ("key")
    WHERE "waqfId" IS NULL;

  -- ─────────────────────────────────────────────────────────────────────────────────────────
  -- 3.6 AUDIT CHAIN HEAD — singleton
  -- ─────────────────────────────────────────────────────────────────────────────────────────
  PERFORM qmulate_add_check('audit_chain_head', 'audit_chain_head_singleton', '"id" = 1');

  -- ─────────────────────────────────────────────────────────────────────────────────────────
  -- 3.7 GRANTS for the least-privilege runtime role (assertion A4)
  -- Skipped with a NOTICE when the role could not be created (see section 2).
  -- ─────────────────────────────────────────────────────────────────────────────────────────
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'qmulate_app_runtime') THEN
    REVOKE ALL ON TABLE "audit_event" FROM PUBLIC;
    GRANT SELECT, INSERT ON TABLE "audit_event" TO qmulate_app_runtime;
    REVOKE UPDATE, DELETE, TRUNCATE ON TABLE "audit_event" FROM qmulate_app_runtime;

    GRANT SELECT, INSERT, UPDATE ON TABLE "audit_chain_head" TO qmulate_app_runtime;
    REVOKE DELETE, TRUNCATE ON TABLE "audit_chain_head" FROM qmulate_app_runtime;

    -- The audit id is allocated with `nextval` INSIDE the transaction (the id is bound into the
    -- row hash, so it must be known before the INSERT). Resolve the sequence name rather than
    -- hard-coding `audit_event_id_seq`, so a Prisma naming change cannot silently break it.
    audit_seq := pg_get_serial_sequence('public."audit_event"', 'id');
    IF audit_seq IS NOT NULL THEN
      EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO qmulate_app_runtime', audit_seq);
    END IF;
  ELSE
    RAISE NOTICE
      'QMULATE: role qmulate_app_runtime does not exist — GRANTs skipped. The append-only '
      'trigger still protects audit_event; assertion A4 will fail until this migration is '
      're-applied with a privileged connection (SELECT qmulate_apply_guards();).';
  END IF;

  -- ═══════════════════════════════════════════════════════════════════════════════════════
  -- 3.7 ENABLE ALWAYS — close the `session_replication_role` bypass
  --
  -- FOUND BY ADVERSARIAL REVIEW, and it defeated gate G-1 outright.
  --
  -- A trigger created normally is `tgenabled = 'O'` (fire on ORIGIN). Postgres skips every
  -- such trigger when the session sets:
  --
  --     SET LOCAL session_replication_role = 'replica';
  --
  -- That is a plain `SET`, not DDL — no `ALTER TABLE`, no `DROP TRIGGER`, no ownership of the
  -- table needed beyond what the app already has. One statement on the ordinary application
  -- connection was enough to `UPDATE` and `DELETE` committed `audit_event` rows, inside the
  -- very transaction that was supposed to be recording the change. The threat model written
  -- above assumed "a DBA with a psql prompt"; the real exposure was the app itself.
  --
  -- `ENABLE ALWAYS` sets `tgenabled = 'A'`, which fires regardless of
  -- `session_replication_role`. Applied to EVERY guard, not just the audit ones — the same
  -- one-liner would otherwise have bypassed the Shart-al-Waqif, corpus and retention guards.
  --
  -- Kept inside `qmulate_apply_guards()` so the documented repair path restores it too.
  -- ═══════════════════════════════════════════════════════════════════════════════════════
  ALTER TABLE "audit_event"      ENABLE ALWAYS TRIGGER audit_event_no_mutate;
  ALTER TABLE "audit_event"      ENABLE ALWAYS TRIGGER audit_event_no_truncate;
  ALTER TABLE "audit_event"      ENABLE ALWAYS TRIGGER audit_event_no_mutate_row;
  ALTER TABLE "audit_chain_head" ENABLE ALWAYS TRIGGER audit_chain_head_no_truncate;
  ALTER TABLE "audit_chain_head" ENABLE ALWAYS TRIGGER audit_chain_head_no_delete;
  ALTER TABLE "audit_chain_head" ENABLE ALWAYS TRIGGER audit_chain_head_forward_only;
  ALTER TABLE "waqf"             ENABLE ALWAYS TRIGGER waqf_shart_immutable;
  ALTER TABLE "document"         ENABLE ALWAYS TRIGGER document_retention_guard;
  ALTER TABLE "document"         ENABLE ALWAYS TRIGGER document_retention_forward_only;
  ALTER TABLE "document"         ENABLE ALWAYS TRIGGER document_no_truncate;
END;
$qm_apply_guards$;


-- ═══════════════════════════════════════════════════════════════════════════════════════════
-- SECTION 4 — APPLY
--
-- ⚠ ORDERING. This migration ALTERs tables it does not create, so it must run AFTER the
-- Prisma-generated init migration. Prisma applies migration directories in lexicographic order
-- of their names, so the init migration's directory must sort BEFORE
-- `00000000000001_init_append_only_audit`. The supported way to get that is to generate the init
-- migration by hand into `00000000000000_init` — see `prisma/sql/README.md`. If the base tables
-- are missing we fail LOUDLY here rather than skipping the guards silently: a database with an
-- unguarded `audit_event` must never be mistaken for a healthy one.
-- ═══════════════════════════════════════════════════════════════════════════════════════════

DO $qm_apply$
DECLARE
  missing text[] := ARRAY[]::text[];
  t       text;
BEGIN
  FOREACH t IN ARRAY ARRAY['audit_event', 'audit_chain_head', 'waqf', 'transaction', 'document', 'setting']
  LOOP
    IF to_regclass(format('public.%I', t)) IS NULL THEN
      missing := missing || t;
    END IF;
  END LOOP;

  IF array_length(missing, 1) IS NOT NULL THEN
    RAISE EXCEPTION
      'QMULATE constraints migration ran BEFORE the Prisma-generated init migration. Missing '
      'table(s): %. This migration must sort AFTER the init migration. Fix: generate the init '
      'migration into prisma/migrations/00000000000000_init/migration.sql with '
      '`prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script`, '
      'or rename this directory to a timestamp later than the existing init migration. '
      'See packages/database/prisma/sql/README.md.',
      array_to_string(missing, ', ');
  END IF;

  PERFORM qmulate_apply_guards();
END
$qm_apply$;
